export const LOAD_STORIES_LIST = "LOAD_STORIES_LIST";
export const LOAD_STORIES_LIST_SUCCESS = "LOAD_STORIES_LIST_SUCCESS";
export const DELETE_STORY = "DELETE_STORY";
export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";

export const API_FAILED = "STORIES_LIST_API_FAILED";