export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
export const WEBSOCKET_CONNECTED = "WEBSOCKET_CONNECTED";
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
export const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
export const SEND_MESSAGE = "SEND_MESSAGE";