export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const VALIDATE_USER_REGISTER = "VALIDATE_USER_REGISTER";
export const VALIDATE_USER_REGISTER_SUCCESS = "VALIDATE_USER_REGISTER_SUCCESS";
export const RESEND_VERIFICATION_CODE = "RESEND_VERIFICATION_CODE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";

export const UPDATE_TOKEN = "UPDATE_TOKEN";

export const LOAD_MONTH_STORIES_COUNT_SUCCESS = "LOAD_MONTH_STORIES_COUNT_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const VALIDATE_NEW_USER_EMAIL = "VALIDATE_NEW_USER_EMAIL";
export const VALIDATE_NEW_USER_EMAIL_SUCCESS = "VALIDATE_NEW_USER_EMAIL_SUCCESS";

export const CHANGE_PASSWORD_LOGGED_USER = "CHANGE_PASSWORD_LOGGED_USER";
export const CHANGE_PASSWORD_LOGGED_USER_SUCCESS = "CHANGE_PASSWORD_LOGGED_USER_SUCCESS";

export const API_FAILED = "AUTH_API_FAILED";

export const DEFAULT_PICTURE_B64 = "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAMAAADXqc3KAAABFFBMVEUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAwUDAwUDAwUDAwUDBAYDBAYDBAYCBAUCBAUEBQYCAwUCAwUDBQYDBQYCAwQJDBACAwQJDA8CAwQIDA8HDA8IDA8JDREHCg4IDA8PFRsCAwQPFRsCAgMCAwQDBAUCAgMCAwQWHicXHygXICkXISoXIisaJjAbJjANEhcYIiwjMT8AAAAOExkaJC8cJzIiMD0kM0EkM0IlNEImNUUnN0YnN0coOEgoOEkoOUkvQlQvQlUwQ1cwRFcxRVkzR1wzSFw0SV7////YywvtAAAARXRSTlMAAQIHDg8WFxkaHjY4QEFDSU9QUVNUVWZnipKSmJuusLPZ2trc39/g4+/w8PHx8vLy8/Pz9PT19fX29vj4+Pr7+/v9/f4dztbYAAAAAWJLR0RbdLyVNAAAAN1JREFUGBl1wYdaglAABtD/ZoO0YYPKlu2JVDhQG7ZNMlIb1v/+DxIfweVidA5CkweF86vCbgYDstU2PffVLGLSRo++npGGKn/DwHUeCq3eZ6Bf1xBZKlIqLkIaL7UotUoaQhOHVBxnEBqpfVL6qA1DWilTKi8jkqq8M/BWSUGxdsnAxSpUY8Yrfe7RKGKmbZce157CgFyTnmYOcUK3O/R0bF0gImY2zS59XWt7VuCXmNsyHUqOtbcwBEDM71gOY9qn+zqwYT3zj5ezdZjfTPB1gjsmauDxKdEtHv7xA6PwalPRRI7MAAAAAElFTkSuQmCC"