export const LOAD_PROFILES_LIST = "LOAD_PROFILES_LIST";
export const LOAD_PROFILES_LIST_SUCCESS = "LOAD_PROFILES_LIST_SUCCESS";

export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";
export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";

export const API_FAILED = "PROFILES_LIST_API_FAILED";